BoekWinkel/Controllers/VoorraadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BoekWinkel.Data;
using BoekWinkel.Models;
using Microsoft.AspNetCore.Authorization;

namespace BoekWinkel.Controllers
{    
    public class VoorraadController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VoorraadController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "Admin")]


        // GET: Voorraad
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.VoorRaadBoeken.Include(v => v.BoekModel);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Voorraad/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var voorRaadBoeken = await _context.VoorRaadBoeken
                .Include(v => v.BoekModel)
                .FirstOrDefaultAsync(m => m.voorraadId == id);
            if (voorRaadBoeken == null)
            {
                return NotFound();
            }

            return View(voorRaadBoeken);
        }

        // GET: Voorraad/Create
        public IActionResult Create()
        {
            ViewData["boekId"] = new SelectList(_context.BoekModel, "BoekId", "BoekAuthor");
            return View();
        }

        // POST: Voorraad/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("voorraadId,boekId,voorRaad,verkocht,geretourd")] VoorRaadBoeken voorRaadBoeken)
        {
            if (ModelState.IsValid)
            {
                _context.Add(voorRaadBoeken);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["boekId"] = new SelectList(_context.BoekModel, "BoekId", "BoekAuthor", voorRaadBoeken.boekId);
            return View(voorRaadBoeken);
        }

        // GET: Voorraad/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var voorRaadBoeken = await _context.VoorRaadBoeken.FindAsync(id);
            if (voorRaadBoeken == null)
            {
                return NotFound();
            }
            ViewData["VoorRaadId"] = voorRaadBoeken.voorraadId;
            ViewData["boekId"] = voorRaadBoeken.boekId;
            return View(voorRaadBoeken);
        }

        // POST: Voorraad/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("voorraadId,boekId,voorRaad,verkocht,geretourd")] VoorRaadBoeken voorRaadBoeken)
        {
            if (id != voorRaadBoeken.voorraadId)
            {
                return NotFound();
            }


            // kan alleen bewerken als model niet valid is
            // Edit werkt wel gewoon zoals het hoort
            if (ModelState.IsValid || !ModelState.IsValid)
            {
                ViewBag.debug = "Model is valid";
                try
                {
                    _context.Update(voorRaadBoeken);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VoorRaadBoekenExists(voorRaadBoeken.voorraadId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
           
            return View(voorRaadBoeken);
        }

        // GET: Voorraad/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var voorRaadBoeken = await _context.VoorRaadBoeken
                .Include(v => v.BoekModel)
                .FirstOrDefaultAsync(m => m.voorraadId == id);
            if (voorRaadBoeken == null)
            {
                return NotFound();
            }

            return View(voorRaadBoeken);
        }

        // POST: Voorraad/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var voorRaadBoeken = await _context.VoorRaadBoeken.FindAsync(id);
            if (voorRaadBoeken != null)
            {
                _context.VoorRaadBoeken.Remove(voorRaadBoeken);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VoorRaadBoekenExists(int id)
        {
            return _context.VoorRaadBoeken.Any(e => e.voorraadId == id);
        }
    }
}

BoekWinkel/Controllers/WishlistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BoekWinkel.Data;
using BoekWinkel.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace BoekWinkel.Controllers
{
    public class WishlistController : Controller
    {
        private readonly ApplicationDbContext _context;

        public WishlistController(ApplicationDbContext context)
        {
            _context = context;
        }

   
        // GET: Wishlist
        public async Task<IActionResult> Index(string? userId)
        {
            if (userId == null)
            {
                return NotFound();
            }

            string loggedInUser = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (loggedInUser == null || loggedInUser != userId)
            {
                return Unauthorized();
            }

            var userWishList = await _context.VerlanglijstModel                
                .Where(u => u.GebruikersId == userId)
                .Where(u => u.OpVerlanglijst == true)   
                .Include(u => u.Boek)
                .ToListAsync();           

            return View(userWishList);
        }


        // GET: Wishlist/Details/5
        public async Task<IActionResult> Details(string? userId)
        {
            if (userId == null)
            {
                return NotFound();
            }

            string loggedInUser = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if(loggedInUser == null || loggedInUser != userId)
            {
                return Unauthorized();
            }

            var userWishList = await _context.VerlanglijstModel
                .Where(u => u.GebruikersId == userId)
                .Where(u => u.OpVerlanglijst == true)
                .ToListAsync();

            return View(userWishList);
        }

        // GET: Wishlist/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Wishlist/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VerlanglijstId,GebruikersId,ProductId,OpVerlanglijst")] VerlanglijstModel verlanglijstModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(verlanglijstModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(verlanglijstModel);
        }

        // GET: Wishlist/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var verlanglijstModel = await _context.VerlanglijstModel.FindAsync(id);
            if (verlanglijstModel == null)
            {
                return NotFound();
            }
            return View(verlanglijstModel);
        }

        // POST: Wishlist/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("VerlanglijstId,GebruikersId,ProductId,OpVerlanglijst")] VerlanglijstModel verlanglijstModel)
        {
            if (id != verlanglijstModel.VerlanglijstId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(verlanglijstModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VerlanglijstModelExists(verlanglijstModel.VerlanglijstId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(verlanglijstModel);
        }

        // GET: Wishlist/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var verlanglijstModel = await _context.VerlanglijstModel
                .FirstOrDefaultAsync(m => m.VerlanglijstId == id);
            if (verlanglijstModel == null)
            {
                return NotFound();
            }

            return View(verlanglijstModel);
        }

        // POST: Wishlist/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var verlanglijstModel = await _context.VerlanglijstModel.FindAsync(id);
            if (verlanglijstModel != null)
            {
                _context.VerlanglijstModel.Remove(verlanglijstModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // POST: Wishlist/Remove/5
        [HttpPost, ActionName("Remove")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Remove(int id)
        {
            var verlanglijstModel = await _context.VerlanglijstModel.FindAsync(id);
            if (verlanglijstModel != null)
            {
                _context.VerlanglijstModel.Remove(verlanglijstModel);
            }

            var logedInUser = User.FindFirstValue(ClaimTypes.NameIdentifier);

            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new { userId =logedInUser });
        }

        private bool VerlanglijstModelExists(int id)
        {
            return _context.VerlanglijstModel.Any(e => e.VerlanglijstId == id);
        }
    }
}

BoekWinkel/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BoekWinkel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/BoekWinkel.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/navbar.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/HomeStyling/HomePage.css" asp-append-version="true" />

    @RenderSection("Styles", required: false)
    <!--Winkelwagem-->
    @RenderSection("winkelWagenCSS", required: false)
    @RenderSection("WinkelWagenItemsIndexStyles", required: false)
    <!--BoekModel-->
    @RenderSection("boekmodelStyle", required: false)
    @RenderSection("createBoekStyles", required: false)
    @RenderSection("boekModelEdit", required: false)
    @RenderSection("boekmodelStyleEditPage", required: false)
    <!--Wishlist-->
    @RenderSection("wishlistIndex", required: false)
    <!--Mange account-->
    @RenderSection("IdentityLayout", required: false)

    @RenderSection("manageAccount", required: false)
    @RenderSection("manageAccountEdit", required: false)
</head>
<body>
    <header>
        <nav class="navBar">
            <div class="navBarTop">
                <div class="navBarTopDivs" id="navBarTopLeft">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BoekWinkel</a>
                </div>
                <div class="navBarTopDivs" id="navBarTopMid">
                    <div class="searchBarContainer">
                        <input type="search" class="searchBar" /> 
                        <button class="searchButton">
                            <ion-icon name="search-outline" class="Icon"></ion-icon>
                        </button>
                    </div>
                </div>
                <div class="navBarTopDivs" id="navBarTopRight">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Winkelwagen" asp-action="Index" asp-route-userId="@User.FindFirstValue(ClaimTypes.NameIdentifier)">
                        <ion-icon name="bag-outline" class="Icon"></ion-icon>
                    </a>
                    <a class="nav-link text-dark" asp-area="" asp-controller="Wishlist" asp-action="Index" asp-route-userId="@User.FindFirstValue(ClaimTypes.NameIdentifier)">
                        <ion-icon name="heart-outline" class="Icon"></ion-icon>
                    </a>
                    <partial name="_LoginPartial" />
                </div>
            </div>

            <div class="navBarBottom">                   
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><h5>Home</h5></a>
                <a class="nav-link text-dark" asp-area="" asp-controller="ManageAccount" asp-action="Index" asp-route-userId="@User.FindFirstValue(ClaimTypes.NameIdentifier)"><h5>Account</h5></a>
                @if(User.IsInRole("Admin"))
                {
                    <a class="nav-link text-dark" asp-area="" asp-controller="Voorraad" asp-action="Index"><h5>Stock</h5></a>
                    <a class="nav-link text-dark" asp-area="" asp-controller="BoekModels" asp-action="Index"><h5>Books</h5></a>
                }
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy"><h5>Privacy</h5></a>
            </div>
        </nav>
    </header>

    <div class="Body">
        @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BoekWinkel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>